t1:
	python3 src/import.py data/551-mw-roster.csv data/551-0125.txt
t2:
	python3 src/stats.py output/task2

t3:
	python3 src/nochats.py output/task3

t4:
	python3 src/search-person.py 'Dhruvil Anil'
t5:
	python3 src/search-message.py 'reid pattis'